spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/{database}
    username:
    password:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO

server:
  port: